[tool.poetry]
name = "oop-training"
version = "0.1.0"
description = ""
authors = ["FireBoy48 <gert48750@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
